services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL_ID=${GEMINI_MODEL_ID}
      - AWS_REGION_NAME=${AWS_REGION_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BEDROCK_MODEL_ID=${BEDROCK_MODEL_ID}
      # Per-model RPM (Requests Per Minute) limits
      - OPENAI_GPT4O_RPM=${OPENAI_GPT4O_RPM}
      - OPENAI_GPT4O_MINI_RPM=${OPENAI_GPT4O_MINI_RPM}
      - GEMINI_25_FLASH_LITE_RPM=${GEMINI_25_FLASH_LITE_RPM}
      - AWS_NOVA_LITE_RPM=${AWS_NOVA_LITE_RPM}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: whisper_db
      POSTGRES_USER: whisper_user
      POSTGRES_PASSWORD: whisper_pass
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:5433:5432"

volumes:
  pgdata:
