# Generated by Django 5.2.5 on 2025-08-29 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_grammargamesession_ggs_user_idx_and_more'),
        ('core', '0010_batchjob_cancel_and_status'),
    ]

    operations = [
    ]
