# Generated by Django 5.2.5 on 2025-08-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_puzzle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
