# Generated by Django 5.2.5 on 2025-09-01 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_puzzle_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('category', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('kanji', 'Kanji'), ('grammar', 'Grammar'), ('phrases', 'Phrases')], max_length=20)),
                ('front', models.TextField(help_text='Front side (Japanese)')),
                ('back', models.TextField(help_text='Back side (English/explanation)')),
                ('reading', models.CharField(blank=True, help_text='Furigana/reading', max_length=255)),
                ('example', models.TextField(blank=True, help_text='Example sentence')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jlpt_level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('category', models.CharField(choices=[('vocabulary', 'Vocabulary'), ('kanji', 'Kanji'), ('grammar', 'Grammar'), ('phrases', 'Phrases')], max_length=20)),
                ('total_cards', models.PositiveIntegerField()),
                ('correct', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
